CATEGORIES = (
    "Action Figures",
    "Adventure Travel",
    "Air Purifiers",
    "Art and Crafts",
    "Baby Clothing",
    "Baby Products",
    "Backpacks",
    "Baking Pans",
    "Baking Supplies",
    "Beach Accessories",
    "Beauty",
    "Board Books",
    "Board Games",
    "Books",
    "Bracelets",
    "Camping Gear",
    "Camping Tents",
    "Car Accessories",
    "Car Care Products",
    "Cleaning Products",
    "Climbing Gear",
    "Coffee Machines",
    "Confectionery",
    "Cookbooks",
    "Cooking Gadgets",
    "Cooking Utensils",
    "Cosmetics",
    "Cycling Accessories",
    "DIY Tools",
    "DIY",
    "Drums",
    "Educational Books",
    "Educational Toys",
    "Electronics",
    "Exercise Equipment",
    "Fashion Accessories",
    "Fashion",
    "Fishing Gear",
    "Fitness",
    "Food and Beverages",
    "GPS Devices",
    "Gadgets",
    "Games",
    "Gardening Tools",
    "Gardening",
    "Gourmet Food",
    "Graphic Novels",
    "Greeting Cards",
    "Haircare Products",
    "Headphones",
    "Health",
    "Hiking Gear",
    "Home Appliances",
    "Home Decor",
    "Home Office",
    "Jewelry",
    "Kitchen Appliances",
    "Luggage",
    "Makeup Brushes",
    "Mouthwash",
    "Music",
    "Musical Instruments",
    "Nutrition",
    "Office Supplies",
    "Outdoor Furniture",
    "Outdoor",
    "Oven Mitts",
    "Paintings",
    "Party Decorations",
    "Party Supplies",
    "Perfumes",
    "Pet Accessories",
    "Pet Food",
    "Pet Supplies",
    "Pet Toys",
    "Phone Accessories",
    "Phone Cases",
    "Photo Printing",
    "Photography",
    "Protein Supplements",
    "Shoes",
    "Skincare Products",
    "Sleeping Bags",
    "Smart Home",
    "Smartphone Accessories",
    "Smartwatches",
    "Sports",
    "Strategy Games",
    "Suitcases",
    "Tea",
    "Toys for Toddlers",
    "Toys",
    "Travel",
    "Treadmills",
    "Video Games",
    "Virtual Reality",
    "Vitamins",
    "Watches",
    "Water Sports",
    "Winter Clothing",
    "Yoga Equipment",
)
